Repository AY2324S2-CS2103T-T16-1/tp, pull requests merged in 2024-03, with the labels that each got.

#8 Update AboutUs (Kumar Prabhat)
  docs/AboutUs.md
  docs/images/dedsecrattle.png
Labels: documentation, type.story

#9 Update Site wide Settings
  docs/_markbind/layouts/default.md
  docs/images/SeEduLogo.png
  docs/images/favicon.png
  docs/site.json
Labels: documentation, enhancement, type.story

#11 Update About Us (Tan Jun Heng)
  docs/AboutUs.md
  docs/images/austintjh19.jpg
Labels: type.story

#13 Update README.md
  README.md
Labels: documentation, type.story

#14 Fix Typo
  README.md
Labels: documentation

#15 Update About Us Image File Format
  docs/AboutUs.md
  docs/images/austintjh19.png
Labels: type.story

#20 Add information to AboutUs
  docs/AboutUs.md
  docs/images/valencialim.png
Labels: type.story

#25 Add Use cases.
  docs/DeveloperGuide.md
Labels: documentation, type.story

#21 Update Developer Guide
  docs/DeveloperGuide.md
Labels: documentation, type.story

#30 Fix DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: documentation, type.story

#31 Edit Use Cases.
  docs/DeveloperGuide.md
Labels: documentation, type.story

#29 Update User Guide for Delete and Filter
  docs/UserGuide.md
Labels: documentation, type.story

#32 Update user guide
  docs/UserGuide.md
Labels: documentation, type.story

#33 Update search feature in User Guide
  docs/UserGuide.md
Labels: documentation, type.story

#42 Implement/Modify Add Command
  src/main/java/seedu/address/model/person/Id.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/model/person/IdTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: enhancement, type.story, priority.High

#49 Modify/Enhance Add Command
  src/main/java/seedu/address/commons/util/JsonUtil.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/grade/Grade.java
  src/main/java/seedu/address/model/grade/Grades.java
  src/main/java/seedu/address/model/person/Id.java
  src/main/java/seedu/address/model/person/Intake.java
  src/main/java/seedu/address/model/person/Major.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/grade/GradeTest.java
  src/test/java/seedu/address/model/person/IdTest.java
  src/test/java/seedu/address/model/person/IntakeTest.java
  src/test/java/seedu/address/model/person/MajorTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: enhancement, type.story, priority.High, severity.High

#53 Modify/ Enhance User Interface
  src/main/resources/images/eduLinkNus.png
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
Labels: enhancement, type.story, priority.Medium

#51 Modify/Enhance Edit Command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: enhancement, type.story, priority.High

#47 Add tag command.
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/TagCommandParser.java
  src/test/java/seedu/address/logic/commands/TagCommandTest.java
  src/test/java/seedu/address/logic/parser/TagCommandParserTest.java
Labels: type.story, priority.High

#40 Add/ Modify search Command
  docs/UserGuide.md
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/IdAndNameContainsQueryIdAndNamePredicate.java
  src/main/java/seedu/address/model/person/IdContainsQueryIdPredicate.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/NameContainsQueryNamePredicate.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/IdAndNameContainsQueryIdAndNamePredicateTest.java
  src/test/java/seedu/address/model/person/IdContainsQueryIdPredicateTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/NameContainsQueryNamePredicateTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.story, priority.High

#58 Fix bug in DeleteCommand for User Story 5
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
Labels: bug, type.story, priority.High

#68 Update UML and UG for tagging.
  docs/UserGuide.md
  docs/diagrams/tag/TagClassDiagram.puml
Labels: documentation

#73 Enhancement of Search Feature Tests
  src/test/java/seedu/edulink/logic/commands/FindCommandTest.java
Labels: enhancement

#74 Implement Undo Command
  src/main/java/seedu/edulink/logic/LogicManager.java
  src/main/java/seedu/edulink/logic/Messages.java
  src/main/java/seedu/edulink/logic/commands/UndoCommand.java
  src/main/java/seedu/edulink/logic/parser/AddressBookParser.java
  src/main/java/seedu/edulink/model/AddressBook.java
  src/main/java/seedu/edulink/model/Model.java
  src/main/java/seedu/edulink/model/ModelManager.java
  src/main/java/seedu/edulink/ui/MainWindow.java
  src/main/java/seedu/edulink/ui/UiManager.java
  src/test/java/seedu/edulink/logic/commands/AddCommandTest.java
  src/test/java/seedu/edulink/logic/commands/UndoCommandTest.java
  src/test/java/seedu/edulink/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/edulink/model/ModelManagerTest.java
Labels: type.story, priority.High

#66 Modify testcase in DeleteCommandTest and DeleteCommandParserTest to remove custom userInput
  src/test/java/seedu/edulink/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/edulink/logic/parser/DeleteCommandParserTest.java
Labels: bug

#39 Add filter command
  src/main/java/seedu/edulink/commons/util/StringUtil.java
  src/main/java/seedu/edulink/logic/commands/FilterCommand.java
  src/main/java/seedu/edulink/logic/parser/AddressBookParser.java
  src/main/java/seedu/edulink/logic/parser/FilterCommandParser.java
  src/main/java/seedu/edulink/model/student/TagsContainQueryTagsPredicate.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/edulink/commons/util/CsvUtilTest.java
  src/test/java/seedu/edulink/commons/util/StringUtilTest.java
  src/test/java/seedu/edulink/logic/commands/FilterCommandTest.java
  src/test/java/seedu/edulink/logic/commands/TagCommandTest.java
  src/test/java/seedu/edulink/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/edulink/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/edulink/model/student/TagsContainQueryTagsPredicateTest.java
  src/test/java/seedu/edulink/testutil/TypicalPersons.java
Labels: type.story, priority.High

#80 Update Undo Command
  src/main/java/seedu/edulink/logic/Messages.java
  src/main/java/seedu/edulink/model/Model.java
  src/main/java/seedu/edulink/model/ModelManager.java
  src/test/java/seedu/edulink/logic/commands/AddCommandTest.java
  src/test/java/seedu/edulink/model/ModelManagerTest.java
Labels: enhancement, type.story, priority.High, severity.High

#79 Update Documentation and Project Website
  docs/index.md
Labels: documentation, type.Task, priority.Medium, severity.Medium

#88 Create codecov.yml
  codecov.yml
Labels: priority.High, severity.Low

#70 Implement Recent Commands
  src/main/java/seedu/edulink/logic/Logic.java
  src/main/java/seedu/edulink/logic/LogicManager.java
  src/main/java/seedu/edulink/model/RecentCommands.java
  src/main/java/seedu/edulink/ui/CommandBox.java
  src/main/java/seedu/edulink/ui/MainWindow.java
  src/main/java/seedu/edulink/ui/RecentCommandPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/RecentCommandPanel.fxml
  src/test/java/seedu/edulink/logic/LogicManagerTest.java
  src/test/java/seedu/edulink/model/RecentCommandsTest.java
Labels: type.story, priority.High

#89 Fix Bugs in AddCommandParser
  src/main/java/seedu/edulink/logic/parser/AddCommandParser.java
  src/main/java/seedu/edulink/logic/parser/AddressBookParser.java
  src/main/java/seedu/edulink/logic/parser/ParserUtil.java
  src/main/java/seedu/edulink/model/student/Intake.java
  src/test/java/seedu/edulink/logic/LogicManagerTest.java
  src/test/java/seedu/edulink/logic/commands/CommandTestUtil.java
  src/test/java/seedu/edulink/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/edulink/model/student/IntakeTest.java
Labels: type.Bug, priority.High, severity.High

#90 Enhance Ui
  src/main/java/seedu/edulink/ui/MainWindow.java
  src/main/java/seedu/edulink/ui/PersonListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
Labels: enhancement, priority.High

#91 Update User feedback Messages
  src/main/java/seedu/edulink/logic/Messages.java
  src/main/java/seedu/edulink/logic/commands/ExportCommand.java
  src/main/java/seedu/edulink/logic/commands/UndoCommand.java
  src/main/java/seedu/edulink/logic/parser/ExportCommandParser.java
  src/main/java/seedu/edulink/logic/parser/ParserUtil.java
  src/test/java/seedu/edulink/logic/parser/ParserUtilTest.java
Labels: enhancement, priority.High, severity.Medium

#92 Add keyboard support for recentCommands
  src/main/java/seedu/edulink/ui/CommandBox.java
  src/main/java/seedu/edulink/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
Labels: enhancement, type.Epic, priority.High, severity.High

#85 Update grade parameter
  src/main/java/seedu/edulink/commons/util/GradeUtil.java
  src/main/java/seedu/edulink/commons/util/StringUtil.java
  src/main/java/seedu/edulink/logic/commands/AddCommand.java
  src/main/java/seedu/edulink/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/edulink/logic/commands/EditCommand.java
  src/main/java/seedu/edulink/logic/commands/EditTagCommand.java
  src/main/java/seedu/edulink/logic/commands/TagCommand.java
  src/main/java/seedu/edulink/logic/parser/AddCommandParser.java
  src/main/java/seedu/edulink/logic/parser/CliSyntax.java
  src/main/java/seedu/edulink/logic/parser/EditCommandParser.java
  src/main/java/seedu/edulink/logic/parser/ParserUtil.java
  src/main/java/seedu/edulink/model/AddressBook.java
  src/main/java/seedu/edulink/model/grade/Course.java
  src/main/java/seedu/edulink/model/grade/Grade.java
  src/main/java/seedu/edulink/model/grade/Score.java
  src/main/java/seedu/edulink/model/student/Student.java
  src/main/java/seedu/edulink/storage/JsonAdaptedGrade.java
  src/main/java/seedu/edulink/storage/JsonAdaptedPerson.java
  src/main/java/seedu/edulink/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/edulink/ui/DetailsCard.java
  src/main/java/seedu/edulink/ui/PersonCard.java
  src/main/resources/view/DetailsCard.fxml
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/edulink/commons/util/CsvUtilTest.java
  src/test/java/seedu/edulink/commons/util/GradeUtilTest.java
  src/test/java/seedu/edulink/commons/util/StringUtilTest.java
  src/test/java/seedu/edulink/logic/commands/CommandTestUtil.java
  src/test/java/seedu/edulink/logic/commands/DeleteTagCommandTest.java
  src/test/java/seedu/edulink/logic/commands/EditStudentDescriptorTest.java
  src/test/java/seedu/edulink/logic/commands/EditTagCommandTest.java
  src/test/java/seedu/edulink/logic/commands/TagCommandTest.java
  src/test/java/seedu/edulink/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/edulink/logic/parser/ParserUtilTest.java
  src/test/java/seedu/edulink/model/AddressBookTest.java
  src/test/java/seedu/edulink/model/grade/CourseTest.java
  src/test/java/seedu/edulink/model/grade/GradeTest.java
  src/test/java/seedu/edulink/model/grade/ScoreTest.java
  src/test/java/seedu/edulink/model/student/IdTest.java
  src/test/java/seedu/edulink/model/student/StudentTest.java
  src/test/java/seedu/edulink/storage/JsonAdaptedGradeTest.java
  src/test/java/seedu/edulink/storage/JsonAdaptedStudentTest.java
  src/test/java/seedu/edulink/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/edulink/testutil/GradeBuilder.java
  src/test/java/seedu/edulink/testutil/PersonBuilder.java
  src/test/java/seedu/edulink/testutil/PersonUtil.java
  src/test/java/seedu/edulink/testutil/TypicalPersons.java
Labels: enhancement, priority.High
