Repository AY2324S2-CS2103T-T16-1/tp, pull requests merged in 2024-04, with the labels that each got.

#93 Add Import Command
  README.md
  src/main/java/seedu/edulink/MainApp.java
  src/main/java/seedu/edulink/logic/LogicManager.java
  src/main/java/seedu/edulink/logic/commands/ImportCommand.java
  src/main/java/seedu/edulink/logic/parser/AddressBookParser.java
  src/main/java/seedu/edulink/logic/parser/ImportCommandParser.java
  src/main/java/seedu/edulink/model/ModelManager.java
  src/main/java/seedu/edulink/storage/Storage.java
  src/main/java/seedu/edulink/storage/StorageManager.java
  src/main/resources/view/DetailsCard.fxml
  src/test/java/seedu/edulink/logic/commands/ImportCommandTest.java
  src/test/java/seedu/edulink/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/edulink/logic/parser/ImportCommandParser.java
Labels: type.story, priority.High, severity.High

#96 Update User GUide
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/UiLayout.png
Labels: documentation, enhancement

#101 Update User Guide
  docs/UserGuide.md
  docs/images/helpMessage.png
Labels: documentation, enhancement

#103 Misc Enhancements
  src/main/java/seedu/edulink/logic/Messages.java
  src/main/java/seedu/edulink/logic/commands/AddCommand.java
  src/main/java/seedu/edulink/logic/commands/DeleteCommand.java
  src/main/java/seedu/edulink/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/edulink/logic/commands/EditCommand.java
  src/main/java/seedu/edulink/logic/commands/EditTagCommand.java
  src/main/java/seedu/edulink/logic/commands/FilterCommand.java
  src/main/java/seedu/edulink/logic/commands/FindCommand.java
  src/main/java/seedu/edulink/logic/commands/ImportCommand.java
  src/main/java/seedu/edulink/logic/commands/ListCommand.java
  src/main/java/seedu/edulink/logic/commands/TagCommand.java
  src/main/java/seedu/edulink/logic/parser/EditCommandParser.java
  src/main/java/seedu/edulink/logic/parser/ImportCommandParser.java
  src/main/java/seedu/edulink/model/util/SampleDataUtil.java
  src/test/java/seedu/edulink/logic/commands/EditStudentDescriptorTest.java
  src/test/java/seedu/edulink/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/edulink/testutil/PersonBuilder.java
  src/test/java/seedu/edulink/testutil/PersonUtil.java
Labels: enhancement, type.Enhancement, priority.Low, severity.Low

#104 Implement grade command and modify grade to store a list of grades
  src/main/java/seedu/edulink/logic/Messages.java
  src/main/java/seedu/edulink/logic/commands/AddCommand.java
  src/main/java/seedu/edulink/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/edulink/logic/commands/EditCommand.java
  src/main/java/seedu/edulink/logic/commands/EditTagCommand.java
  src/main/java/seedu/edulink/logic/commands/GradeCommand.java
  src/main/java/seedu/edulink/logic/commands/TagCommand.java
  src/main/java/seedu/edulink/logic/parser/AddCommandParser.java
  src/main/java/seedu/edulink/logic/parser/AddressBookParser.java
  src/main/java/seedu/edulink/logic/parser/CliSyntax.java
  src/main/java/seedu/edulink/logic/parser/GradeCommandParser.java
  src/main/java/seedu/edulink/logic/parser/ParserUtil.java
  src/main/java/seedu/edulink/model/grade/Course.java
  src/main/java/seedu/edulink/model/grade/Grade.java
  src/main/java/seedu/edulink/model/grade/Module.java
  src/main/java/seedu/edulink/model/student/Student.java
  src/main/java/seedu/edulink/storage/JsonAdaptedGrade.java
  src/main/java/seedu/edulink/storage/JsonAdaptedPerson.java
  src/main/java/seedu/edulink/ui/DetailsCard.java
  src/main/java/seedu/edulink/ui/PersonCard.java
  src/main/resources/view/DetailsCard.fxml
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/edulink/logic/commands/CommandTestUtil.java
  src/test/java/seedu/edulink/logic/commands/DeleteTagCommandTest.java
  src/test/java/seedu/edulink/logic/commands/EditStudentDescriptorTest.java
  src/test/java/seedu/edulink/logic/commands/EditTagCommandTest.java
  src/test/java/seedu/edulink/logic/commands/TagCommandTest.java
  src/test/java/seedu/edulink/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/edulink/logic/parser/ImportCommandParserTest.java
  src/test/java/seedu/edulink/logic/parser/ParserUtilTest.java
  src/test/java/seedu/edulink/model/grade/CourseTest.java
  src/test/java/seedu/edulink/model/grade/GradeTest.java
  src/test/java/seedu/edulink/model/grade/ModuleTest.java
  src/test/java/seedu/edulink/model/student/StudentTest.java
  src/test/java/seedu/edulink/storage/JsonAdaptedGradeTest.java
  src/test/java/seedu/edulink/storage/JsonAdaptedStudentTest.java
  src/test/java/seedu/edulink/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/edulink/testutil/GradeBuilder.java
  src/test/java/seedu/edulink/testutil/PersonBuilder.java
  src/test/java/seedu/edulink/testutil/TypicalPersons.java
Labels: enhancement, priority.High

#106 Update UserGuide
  docs/UserGuide.md
  docs/images/RecentCommands.png
Labels: documentation, type.Enhancement

#112 Fix UserGuide Issues
  docs/UserGuide.md
Labels: documentation

#113 Add delete grade feature
  src/main/java/seedu/edulink/logic/commands/DeleteGradeCommand.java
  src/main/java/seedu/edulink/logic/commands/GradeCommand.java
  src/main/java/seedu/edulink/logic/parser/AddressBookParser.java
  src/main/java/seedu/edulink/logic/parser/DeleteGradeCommandParser.java
Labels: enhancement, priority.High

#110 Implemented delete all feature to DeleteCommand
  src/main/java/seedu/edulink/logic/commands/DeleteCommand.java
  src/main/java/seedu/edulink/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/edulink/model/AddressBook.java
  src/main/java/seedu/edulink/model/Model.java
  src/main/java/seedu/edulink/model/ModelManager.java
  src/test/java/seedu/edulink/logic/commands/AddCommandTest.java
Labels: type.Enhancement, priority.Medium

#108 Fix Bugs
  src/main/java/seedu/edulink/model/tag/Tag.java
Labels: bug, enhancement, type.Bug, severity.High

#105 Update User Guide
  docs/UserGuide.md
  docs/images/Index.png
  docs/images/deleteAll.png
Labels: documentation

#115 Add Glossary
  docs/UserGuide.md
Labels: documentation, enhancement

#119 Fix Bugs
  docs/UserGuide.md
  src/main/java/seedu/edulink/logic/Messages.java
  src/main/java/seedu/edulink/model/grade/Grade.java
  src/main/java/seedu/edulink/model/grade/Score.java
  src/main/java/seedu/edulink/ui/DetailsCard.java
  src/main/java/seedu/edulink/ui/PersonCard.java
  src/test/java/seedu/edulink/model/grade/ScoreTest.java
Labels: bug

#173 Fix PE-D Bugs
  src/main/java/seedu/edulink/commons/util/CounterUtil.java
  src/main/java/seedu/edulink/logic/Logic.java
  src/main/java/seedu/edulink/logic/LogicManager.java
  src/main/java/seedu/edulink/logic/commands/ClearCommand.java
  src/main/java/seedu/edulink/logic/parser/AddressBookParser.java
  src/main/java/seedu/edulink/logic/parser/ExportCommandParser.java
  src/main/java/seedu/edulink/logic/parser/ImportCommandParser.java
  src/main/java/seedu/edulink/logic/parser/ParserUtil.java
  src/main/java/seedu/edulink/logic/parser/UndoCommandParser.java
  src/main/java/seedu/edulink/model/student/Email.java
  src/main/java/seedu/edulink/model/student/Name.java
  src/main/java/seedu/edulink/ui/CommandBox.java
  src/main/java/seedu/edulink/ui/MainWindow.java
  src/main/java/seedu/edulink/ui/RecentCommandPanel.java
  src/test/java/seedu/edulink/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/edulink/logic/parser/ExportCommandParserTest.java
  src/test/java/seedu/edulink/model/student/NameTest.java
  src/test/java/seedu/edulink/model/student/StudentTest.java
Labels: bug, priority.High

#174 Fix Invalid prefix for Find & Filter Command
  src/main/java/seedu/edulink/logic/parser/FilterCommandParser.java
  src/main/java/seedu/edulink/logic/parser/FindCommandParser.java
  src/test/java/seedu/edulink/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/edulink/logic/parser/FindCommandParserTest.java
Labels: bug

#176 Fix Ui issues
  src/main/java/seedu/edulink/logic/parser/EditCommandParser.java
  src/main/java/seedu/edulink/model/student/Address.java
  src/main/java/seedu/edulink/ui/MainWindow.java
  src/main/java/seedu/edulink/ui/PersonListPanel.java
Labels: bug, priority.High

#177 Pe bug fixing
  docs/UserGuide.md
  src/main/java/seedu/edulink/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/edulink/logic/commands/EditTagCommand.java
  src/main/java/seedu/edulink/logic/commands/TagCommand.java
Labels: bug, type.Bug, severity.High

#184 Optimize CLI
  src/main/java/seedu/edulink/commons/util/CounterUtil.java
  src/main/java/seedu/edulink/logic/Logic.java
  src/main/java/seedu/edulink/logic/LogicManager.java
  src/main/java/seedu/edulink/ui/CommandBox.java
Labels: bug, enhancement

#186 Fix Invalid Prefix Bug
  src/main/java/seedu/edulink/logic/parser/AddCommandParser.java
  src/main/java/seedu/edulink/logic/parser/EditCommandParser.java
  src/main/java/seedu/edulink/logic/parser/ExportCommandParser.java
  src/main/java/seedu/edulink/logic/parser/FilterCommandParser.java
  src/main/java/seedu/edulink/logic/parser/FindCommandParser.java
  src/main/java/seedu/edulink/logic/parser/ImportCommandParser.java
  src/main/java/seedu/edulink/logic/parser/ParserUtil.java
Labels: bug

#180 Fix Userguide
  docs/UserGuide.md
  src/main/java/seedu/edulink/model/student/Address.java
  src/test/java/seedu/edulink/model/student/AddressTest.java
Labels: documentation, type.Bug, priority.High, severity.High

#188 Solve case-sensitive and invalid prefix bug for tag
  docs/UserGuide.md
  src/main/java/seedu/edulink/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/edulink/logic/commands/EditTagCommand.java
  src/main/java/seedu/edulink/logic/commands/TagCommand.java
  src/main/java/seedu/edulink/logic/parser/DeleteTagCommandParser.java
  src/main/java/seedu/edulink/logic/parser/EditTagCommandParser.java
  src/main/java/seedu/edulink/logic/parser/TagCommandParser.java
  src/main/java/seedu/edulink/model/tag/Tag.java
  src/test/java/seedu/edulink/commons/util/CsvUtilTest.java
Labels: bug, documentation, priority.High

#182 Fix issues in bug report
  docs/UserGuide.md
  src/main/java/seedu/edulink/commons/util/StringUtil.java
  src/main/java/seedu/edulink/logic/commands/DeleteGradeCommand.java
  src/main/java/seedu/edulink/logic/commands/GradeCommand.java
  src/main/java/seedu/edulink/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/edulink/logic/parser/DeleteGradeCommandParser.java
  src/main/java/seedu/edulink/logic/parser/GradeCommandParser.java
  src/main/java/seedu/edulink/logic/parser/ParserUtil.java
  src/main/java/seedu/edulink/model/grade/Module.java
  src/main/java/seedu/edulink/model/grade/Score.java
Labels: bug, type.Bug, priority.High, severity.Medium

#192 Update User Guide
  docs/UserGuide.md
  docs/team/dedsecrattle.md
  src/main/java/seedu/edulink/commons/util/StringUtil.java
Labels: bug, documentation

#193 Incorporate Grades into export
  src/main/java/seedu/edulink/commons/util/CsvUtil.java
  src/main/java/seedu/edulink/model/grade/Grade.java
  src/test/java/seedu/edulink/commons/util/CsvUtilTest.java
Labels: bug, priority.High, severity.High

#194 Automatic removal of duplicated whitespaces
  src/main/java/seedu/edulink/commons/util/UserInputUtil.java
  src/main/java/seedu/edulink/logic/parser/FilterCommandParser.java
  src/main/java/seedu/edulink/logic/parser/FindCommandParser.java
  src/main/java/seedu/edulink/model/student/Address.java
  src/main/java/seedu/edulink/model/student/Major.java
  src/main/java/seedu/edulink/model/student/Name.java
  src/main/java/seedu/edulink/model/student/predicates/IdAndNameContainsQueryIdAndNamePredicate.java
  src/main/java/seedu/edulink/model/student/predicates/IdContainsQueryIdPredicate.java
  src/main/java/seedu/edulink/model/student/predicates/NameContainsQueryNamePredicate.java
  src/main/java/seedu/edulink/model/student/predicates/TagsContainQueryTagsPredicate.java
  src/test/java/seedu/edulink/logic/commands/CommandTestUtil.java
  src/test/java/seedu/edulink/logic/commands/FilterCommandTest.java
  src/test/java/seedu/edulink/logic/commands/FindCommandTest.java
  src/test/java/seedu/edulink/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/edulink/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/edulink/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/edulink/model/ModelManagerTest.java
  src/test/java/seedu/edulink/model/student/IdAndNameContainsQueryIdAndNamePredicateTest.java
  src/test/java/seedu/edulink/model/student/IdContainsQueryIdPredicateTest.java
  src/test/java/seedu/edulink/model/student/NameContainsQueryNamePredicateTest.java
  src/test/java/seedu/edulink/model/student/TagsContainQueryTagsPredicateTest.java
Labels: bug, priority.Medium, severity.Medium

#196 Sequence Diagram - Find
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/find/FindSequenceDiagram.puml
  hs_err_pid12397.jfr
Labels: documentation

#195 Update Developer Guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  src/main/java/seedu/edulink/commons/util/GradeUtil.java
  src/main/java/seedu/edulink/model/grade/Grade.java
  src/main/java/seedu/edulink/model/grade/LetterGrades.java
  src/test/java/seedu/edulink/commons/util/GradeUtilTest.java
Labels: documentation

#197 Add Implementation Details for Find Feature.
  docs/DeveloperGuide.md
  docs/diagrams/find/FindParserSequenceDiagram.puml
  docs/diagrams/find/FindSequenceDiagram.puml
Labels: documentation

#199 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/export/ExportClassDiagram.puml
  docs/diagrams/export/ExportSequenceDiagram.puml
  docs/diagrams/import/ImportClassDiagram.puml
  docs/diagrams/import/ImportSequenceDiagram.puml
  src/main/java/seedu/edulink/logic/commands/ExportCommand.java
Labels: documentation

#198 Update DG to include TAG related use cases
  docs/DeveloperGuide.md
Labels: documentation, priority.High, severity.High

#200 Update DG - Add Feature
  docs/DeveloperGuide.md
  docs/diagrams/add/AddActivityDiagram.puml
  docs/diagrams/add/AddClassDiagram.puml
  docs/diagrams/find/FindClassDiagram.puml
Labels: documentation

#201 Update CSS for DG & UG
  docs/stylesheets/main.css
Labels: documentation

#202 Update DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ParserClasses.puml
  docs/diagrams/undo/UndoClassDiagram.puml
  docs/diagrams/undo/UndoSequenceDiagram.puml
Labels: documentation

#203 Update use cases for delete, grade and delete grade
  docs/DeveloperGuide.md
Labels: documentation

#204 Minor Changes in Documentation
  docs/AboutUs.md
  docs/SettingUp.md
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  src/main/java/seedu/edulink/logic/commands/AddCommand.java
  src/main/java/seedu/edulink/model/student/Name.java
Labels: documentation, enhancement

#205 Update Message Constraints
  src/main/java/seedu/edulink/model/student/Name.java
Labels: enhancement

#206 Update UG Design
  docs/stylesheets/main.css
Labels: documentation

#207 Update UG hyperlinks
  docs/UserGuide.md
Labels: documentation

#209 Add implementation and UML diagrams for Grade feature
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/grade/GradeActivityDiagram.puml
  docs/diagrams/grade/GradeClassDiagram.puml
  docs/diagrams/grade/GradeSequenceDiagram.puml
Labels: documentation

#212 Update user stories
  docs/DeveloperGuide.md
Labels: documentation

#214 Update tag implementation in DG
  docs/DeveloperGuide.md
  docs/diagrams/tag/TagSequenceDiagram.puml
Labels: documentation

#213 Update tag related UG issues and fix tag length restriction issue
  docs/UserGuide.md
  src/main/java/seedu/edulink/model/tag/Tag.java
Labels: bug, documentation, severity.High

#215 Update UG
  docs/UserGuide.md
  src/main/resources/view/HelpWindow.css
Labels: documentation

#217 Fix Minor Errors
  src/main/java/seedu/edulink/logic/commands/ExportCommand.java
  src/main/java/seedu/edulink/logic/commands/ImportCommand.java
  src/main/java/seedu/edulink/logic/commands/UndoCommand.java
  src/main/java/seedu/edulink/logic/parser/UndoCommandParser.java
Labels: documentation

#221 Fix ug summary
  docs/UserGuide.md
Labels: bug, documentation
